# encoding: utf-8
---
recipe:
  Rx: others/recipes/config
  args:
    - schema=flypy
  description: >-
    暂时不知道干嘛的

patch_files:
  radical_pinyin.custom.yaml:
    - patch/+:
        speller/algebra:
          __include: radical_pinyin.schema.yaml:/algebra_${schema:-flypy}
  melt_eng.custom.yaml:
    - patch/+:
        speller/algebra:
          __include: melt_eng.schema.yaml:/algebra_${schema:-flypy}
